version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    ports:
      - '8080:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root

  rabbitmq_custom_vhost:
    image: rabbitmq:3.13.1-management-alpine
    ports:
      - '8081:15672'
      - '5673:5672'
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
      RABBITMQ_DEFAULT_VHOST: example_vhost
