services:
  backend:
    build:
      dockerfile: examples/in-memory-async/Dockerfile
      context: ../../
    restart: on-failure
    ports:
      - '8080:8080'
      - '5005:5005'

  postgresql:
    image: postgres:17.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    ports:
      - '5434:5432'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example

volumes:
  postgres:
