services:
  backend:
    image: books_marketplace_in_memory_async:0.0.5
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"
    ports:
      - '8080:8080'
      - '5005:5005'

  postgresql:
    image: postgres:17.0-alpine
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example

volumes:
  postgres:
