services:
  backend:
    image: books_marketplace_rabbitmq_polling:latest
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    ports:
      - '8080:8080'

  consumer:
    image: books_marketplace_rabbitmq_polling:latest
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    environment:
      CONSUMER_MODE: 'true'

  postgresql:
    image: postgres:17.0-alpine
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example

  rabbitmq:
    image: rabbitmq:4.0.3-management-alpine
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres:
