services:
  backend:
    build:
      dockerfile: examples/in-memory/Dockerfile
      context: ../../
    ports:
      - '8082:8080'

  consumer:
    build:
      dockerfile: examples/in-memory/Dockerfile
      context: ../../
    environment:
      CONSUMER_MODE: true

  postgresql:
    image: postgres:17.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example

  rabbitmq:
    image: rabbitmq:4.0.3-management-alpine
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres:
