services:
  backend:
    build:
      dockerfile: examples/rabbitmq/Dockerfile
      context: ../../
    restart: on-failure
    ports:
      - '8080:8080'
      - '5005:5005'

  consumer:
    build:
      dockerfile: examples/rabbitmq/Dockerfile
      context: ../../
    restart: on-failure
    ports:
      - '5006:5005'
    environment:
      CONSUMER_MODE: 'true'

  postgresql:
    image: postgres:17.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    ports:
      - '5434:5432'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example

  rabbitmq:
    image: rabbitmq:4.0.3-management-alpine
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres:
